### ISSUE TITLE
Implement storing session after restarting VSCode IDE.

### ISSUE THREAD

**Issue by rugpanov** [JetBrains/teamcity-vscode-extension#11]
The extension should store session even after restarting VSCode. 
We should implement storing user credentials on a disk.

**Comment by rugpanov** [comment]
According to https://github.com/Microsoft/vscode/issues/30209 and https://github.com/Microsoft/vscode/issues/15414 Microsoft are planning to provide a secure credential storage API in the near future. From the same thread: "VSTS Build Status extension stores password in settings currently, which is not secure." . 

From my perspective there are two approach: don't provide any storage till Microsoft provides any secure one OR we can implement an insecure storage and then replace it by secure when it's possible. @dtretyakov, what is your opinion?

**Comment by dtretyakov** [comment]
@rugpanov, we could try to leverage https://github.com/atom/node-keytar to store credentials until VSCode will bring own credentials store.

**Comment by rugpanov** [comment]
@dtretyakov, I was looking at this module, but it requires python on user's PC. We discussed this problem with Igor and then I decided not to use it. I am afraid because of this problem we cannot use levelUp as well.

**Comment by dtretyakov** [comment]
@rugpanov, you could take a look at the keytar with prebuild binaries, produced by our colleague: https://www.npmjs.com/package/keytar-prebuild

**Comment by rugpanov** [comment]
During installing by "npm install keytar-prebuild --arch=ia32" I got an error: "Can't find Python executable "python", you can set the PYTHON env variable." again.

**Comment by rugpanov** [comment]
New error for Win10: 
> A dynamic link library (DLL) initialization routine failed.

I've fount an closed issue: https://github.com/atom/node-keytar/issues/51, but:
> npm install keytar --save-dev electron-rebuild --arch=ia32

doesn't work for me as well.

**Comment by dtretyakov** [comment]
The discussion regarding Credentials API in VS Code: https://github.com/Microsoft/vscode/issues/31131

**Comment by ehaackXceligent** [comment]
Just a thought: (At least with .0.0.2,) it is storing the Tc URL, username... just not the password. 

I don't think it's too much to ask for devs to re-enter their Tc password on restart.

**Comment by rugpanov** [comment]
Fixed at ec6ea4b06cd15c9eaac0f63660ef4b9cf956b6c6 .
