### ISSUE TITLE
Where is "tc.vsix"?

### ISSUE THREAD

**Issue by mauvehed** [JetBrains/teamcity-vscode-extension#21]
From the README.md

> Type "Install from VSIX" and choose the tc.vsix file in the opened dialoge box

Where does one get _tc.vsix_? Clearly I'm missing something obvious here.

**Comment by mauvehed** [comment]
Any reason this isn't simply available in the [Extensions Marketplace](https://marketplace.visualstudio.com/)?

**Comment by rugpanov** [comment]
Currently the extension is at a development stage. It doesn't cover some important features and it wasn't validated by our QA team. That's the main reason why it's not available in the Extensions Marketplace now. 

You can find all pre-released versions(with .vsix artifacts) on [corresponded page.](https://github.com/JetBrains/teamcity-vscode-extension/releases) Also I would like to say that previous release was several month ago and from that time we implemented some great features. I expect we release new version of TeamCity extension for VSCode till the end of the year (on this week).
