### ISSUE TITLE
Unknown XML-RPC tag 'TITLE'

### ISSUE THREAD

**Issue by gilluminate** [JetBrains/teamcity-vscode-extension#35]
When attempting to log in, I am receiving an error message
`(TeamCity) Unknown XML-RPC tag 'TITLE'`

The authentication doesn't work and every time I attempt to add my credentials I get this same message.

Installed version: teamcity-vscode-extension-1.0.0-beta.6.vsix
MacOS: 10.13.5 (High Sierra)
VSCode: 1.24.0

**Comment by rugpanov** [comment]
Thank you for the report.

If there is an  HTTPS connection, the problem can be related to the way of creation of xmlrpc client. 
Please try [this custom build](https://github.com/JetBrains/teamcity-vscode-extension/files/2096833/teamcity-vscode-extension-1.0.0-beta.6-bugfix1.vsix.zip)

**Comment by gilluminate** [comment]
That worked. Thank you.

**Comment by rugpanov** [comment]
This fix will be added to the next release.

**Comment by rugpanov** [comment]
@gilluminate, please check out this version.

**Comment by gilluminate** [comment]
Working well. Thank you!
