### ISSUE TITLE
Https Support

### ISSUE THREAD

**Issue by amolds** [JetBrains/teamcity-vscode-extension#38]
Providing a https url to sign in results in (TeamCity) socket hang up.  Looks like default is port 80 and this can't be overriden.

**Comment by rugpanov** [comment]
Thank you for the report

fixed at https://github.com/JetBrains/teamcity-vscode-extension/commit/9c78807fd1caf3c66ee32ae78bea4b7524d0c5b7 . 

I'll prepare a new release with these changes soon.

**Comment by rugpanov** [comment]
@amolds, please check out [this version](https://github.com/JetBrains/teamcity-vscode-extension/releases/tag/v1.0.0-beta.7).

**Comment by amolds** [comment]
@rugpanov Works like a champ.  Thanks for the quick fix!
